name: Python Library CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Zmiana na Windows

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      # Pobranie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Zainstalowanie wybranej wersji Pythona
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Instalacja zależności (np. z requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Uruchomienie testów
      - name: Run tests
        run: |
          pytest
